model_name: UNet  # only unet supported
image_size: [128, 128]

train:
  validation_schedule:
    - [0, 1, 2, 3]
    - [7, 11, 13, 18]
    - [20, 23, 27, 30]
  epochs: 200
  batch_size: 64
  patience: 20
  num_classes: 2

  loss:
    name: "wcce"  # weighted categorical cross entropy (wcce), dice, or bce_dice
#    class_weights: [0.15, 0.85]

  optimizer:
    name: "adam"  # choose between adam and sgd
    lr: 0.02
    decay: 0.5
    decay_rate: 10

  preprocess:
    - name: "RandomScale"
      args:
        scaling_limit: 0.1
    - name: "RandomShift"
      args:
        shift_factor: 0.1
    - name: "RandomFlip"
    - name: "RandomRotation"